version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u sjega93 -p Ruby240895!
  build:
    commands:
      - docker build -t sjega93/test:newversionFFHS .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker images
      - docker push sjega93/test:newversionFFHS
      - echo Writing image definitions file...
      - printf '{"ImageURI":"sjega93/test:newversionFFHS"}' > imageDetail.json
artifacts:
  files: 
    - 'imageDetail.json'
    - 'appspec.yml'
    - 'appspec2.yml'
    - 'taskdef.json'
    - 'taskdef2.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yml
        - taskdef.json
        - appspec2.yml
        - taskdef2.json
    ImageArtifact:
      files:
        - imageDetail.json